### ISSUE TITLE
Clean up

### ISSUE THREAD

**Issue by effordDev** [effordDev/sf-application#37]

**Comment by effordDev** [comment]
ApplicationDetail__c.InputOrDisplayClass__c

```ruby
if( CONTAINS(RecordType.DeveloperName, 'Input') || CONTAINS(RecordType.DeveloperName, 'Custom'),
 'customInput', 
 'customDisplay'
 ) 
```

**Comment by effordDev** [comment]
ApplicationProgressIndicatorMain.lwc
```js
setInitialActiveSection(sections) {

   if (sections.every(s => s.Completed__c)) {
      this.activeSectionId = (sections[sections.length - 1])?.Id
      return
   }

      this.activeSectionId` = (sections.find(s => !s.Completed__c))?.Id
}
```

**Comment by effordDev** [comment]
applicationProgressIndicatorMain.css

```css
.questionsWrapper {
    /* border: 1px solid rgb(0, 42, 255); */
    padding: 5px;
    height: fit-content;
    max-height: 100vh;
    overflow-y: scroll;
}
```
